### ISSUE TITLE
Lost IP config

### ISSUE THREAD

**Issue by klone7474** [gwojcieszczuk/kms4vsphere#2]
Somehow it lost it ipv4 configuration and is no longer reachable. after reboot it gets an IP 10.142.81.1 which is not my range. in which file can i change that to 192.x.x.x

**Comment by gwojcieszczuk** [comment]
In this appliance, I'm not using persistent configuration file for network settings. Have a look at /root/config-net.sh file; this is a script responsible for figuring out networking settings based on the values provided when appliance was deployed. Is you vcenter running?

**Comment by klone7474** [comment]
Yes vcenter is running. I will have a look on the file as you mention. I think the vmotion did mix it up.
    On Thursday, 3 February 2022, 09:26:18 GMT, Greg W. ***@***.***> wrote:  
 
 


In this appliance, I'm not using persistent configuration file for network settings. Have a look at /root/config-net.sh file; this is a script responsible for figuring out networking settings based on the values provided when appliance was deployed. Is you vcenter running?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by klone7474** [comment]
I run into small problem, access denied to /root/config-net.sh as I am using kmip user. i try to use passwd root and not allowed.It is also possible that I the stupid one.
    On Thursday, 3 February 2022, 09:26:18 GMT, Greg W. ***@***.***> wrote:  
 
 


In this appliance, I'm not using persistent configuration file for network settings. Have a look at /root/config-net.sh file; this is a script responsible for figuring out networking settings based on the values provided when appliance was deployed. Is you vcenter running?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gwojcieszczuk** [comment]
When you log int as kmip user, run this command: sudo -i   
You will be prompted to enter user kmip password (Passw0rd). This will allow you to switch to user root account and view that file.. You can also run it and tell me if it reports anything. 

```console
/root/config-net.sh
```

**Comment by klone7474** [comment]
On Thursday, 3 February 2022, 12:01:14 GMT, Greg W. ***@***.***> wrote:  
 
 


When you log int as kmip user, run this command: sudo -i
You will be prompted to enter user kmip password (Passw0rd). This will allow you to switch to user root account and view that file.. You can also run it and tell me if it reports anything.
/root/config-net.sh
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by klone7474** [comment]
Ok i checked the file /tmp/ovfenv.xml and that is empty and by booting i notice he can't boot network. so i created on a new vcenter on different system a new KMS and did look into the same file and I found the right content what should be inside.
Can I copy the content from one KMS of ovfenv.xml to another kms and modify the mac address and ve:network so that it suits the kms and reboot that VM?
    On Thursday, 3 February 2022, 12:01:14 GMT, Greg W. ***@***.***> wrote:  
 
 


When you log int as kmip user, run this command: sudo -i
You will be prompted to enter user kmip password (Passw0rd). This will allow you to switch to user root account and view that file.. You can also run it and tell me if it reports anything.
/root/config-net.sh
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by klone7474** [comment]
i did try to modify the file ovfenv.xml and after reboot it is empty again.interesting.
    On Thursday, 3 February 2022, 12:01:14 GMT, Greg W. ***@***.***> wrote:  
 
 


When you log int as kmip user, run this command: sudo -i
You will be prompted to enter user kmip password (Passw0rd). This will allow you to switch to user root account and view that file.. You can also run it and tell me if it reports anything.
/root/config-net.sh
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gwojcieszczuk** [comment]
The ovfenv.xml file is generated dynamically from output of another command. config-net.sh script is triggered every time the appliance reboots. What do you see in ovfenv.xml file?

**Comment by klone7474** [comment]
The file ovfenv.xml in the /tmp folder was empty
    On Thursday, 3 February 2022, 15:06:32 GMT, Greg W. ***@***.***> wrote:  
 
 


The ovfenv.xml file is generated dynamically from output of another command. config-net.sh script is triggered every time the appliance reboots. What do you see in ovfenv.xml file?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gwojcieszczuk** [comment]
That means that vmware tools are unable to request certain properties from vcenter for some reason.
Anyways, you can always delete config-net.sh script and configure networking (and iptables port-forwarding manually). Are you up to quick zoom session tomorrow (i'm in UTC) where I can help you configure this in your env?

**Comment by gwojcieszczuk** [comment]
In the meantime i will try to come up with new script that you can use to configure network settings manually on this appliance, without relying on info obtained from vcenter.

**Comment by klone7474** [comment]
Yes we can make zoom. I am in UK. what time suits you?
    On Thursday, 3 February 2022, 17:07:31 GMT, Greg W. ***@***.***> wrote:  
 
 


That means that vmware tools are unable to request certain properties from vcenter for some reason.
Anyways, you can always delete config-net.sh script and configure networking (and iptables port-forwarding manually). Are you up to quick zoom session tomorrow (i'm in UTC) where I can help you configure this in your env?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gwojcieszczuk** [comment]
Let say 11am. https://Dell.zoom.us/j/5201194768

**Comment by gwojcieszczuk** [comment]
Copy this zoom link. I will remove this post.

**Comment by klone7474** [comment]
You right the guest tools are not installed. ok see you in the meeting.
    On Thursday, 3 February 2022, 17:22:46 GMT, Greg W. ***@***.***> wrote:  
 
 


Copy this zoom link. I will remove this post.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by djspinburner** [comment]
Hi, I have the same issue. been beating my head against a keyboard. I was able to set IP manually but NAT doesn't work for some reason. Maybe you can help me as well if you are willing. I have keys stored on this machine and cannot move VMs between hosts in a cluster. big mess. Let me know if you can help me.
